CREATE TABLE book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_name varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    key varchar(50) UNIQUE NOT NULL,
    status varchar(100) NOT NULL,
    created timestamp with time zone NOT NULL DEFAULT NOW(),
    created_by varchar(100) NOT NULL DEFAULT '',
    last_modified timestamp with time zone NOT NULL DEFAULT NOW(),
    last_modified_by varchar(100) NOT NULL DEFAULT ''
);

CREATE INDEX idx_books_bookname ON book (book_name);

-------------------------------------------------------------------
CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    email varchar(50) NOT NULL,
    password varchar(100) UNIQUE NOT NULL,
    role varchar(50) NOT NULL,
    created timestamp with time zone NOT NULL DEFAULT NOW(),
    created_by varchar(100) NOT NULL DEFAULT '',
    last_modified timestamp with time zone NOT NULL DEFAULT NOW(),
    last_modified_by varchar(100) NOT NULL DEFAULT ''
);

CREATE INDEX idx_user_name ON users (name);

-------------------------------------------------------------------
CREATE TABLE book_transaction (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(50) NOT NULL,
    issued_on TIMESTAMP NOT NULL,
    return_on TIMESTAMP NOT NULL,
    id_user integer NOT NULL REFERENCES users,
    id_book integer NOT NULL REFERENCES book,
    created timestamp with time zone NOT NULL DEFAULT NOW(),
    created_by varchar(100) NOT NULL DEFAULT '',
    last_modified timestamp with time zone NOT NULL DEFAULT NOW(),
    last_modified_by varchar(100) NOT NULL DEFAULT ''
);